# https://www.elastic.co/guide/en/beats/filebeat/current/setup-repositories.html
- name: Import a repo key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Copy elastic.repo file
  ansible.builtin.copy:
    src: ../files/elastic.repo
    dest: /etc/yum.repos.d/elastic.repo
    owner: root
    group: root
    mode: '0644'

- name: Install the newest version of filebeat7.x
  yum:
    name: filebeat
    state: present

- name: Start filebeat
  ansible.builtin.systemd: 
    name: filebeat
    enabled: yes
    state: started
