- name: Config Ubuntu22 Network
  hosts: test
  gather_facts: true
  roles:
    - network
  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - bsdgames
          - net-tools
          - traceroute
    - name: 添加 ARP 表项
      command: arp -s ${路由地址} 网卡mac地址
    - name: 检查 Gateway
      command: route -n | grep -E '0.0.0.0\s+${路由地址}'
      register: gateway_result
    - name: 检查是否能 ping ${IP}
      command: ping -c 2 ${IP}
      ignore_errors: yes
      register: ping_result
    - name: 成功则打印Success
      debug:
        msg: "Success"
      when: ping_result.failed == false and gateway_result.failed == false
      # when: not gateway_result.failed
    # - name: 显示 Gateway 结果
    #   debug:
    #     var: gateway_result.stdout_lines
  # - name: 显示 ping 结果
    #   debug:
    #     var: ping_result.stdout_lines
