- name: zephyr_xmrig
  hosts: test
  become: true
  gather_facts: false
  tasks:
    - name: Ping
      ansible.builtin.ping:
    - name: Creates directory
      ansible.builtin.file:
        path: /opt/zephyr
        state: directory
        mode: '0744'
    - name: Scp xmrig
      ansible.builtin.copy:
        src: ./scrypts/localxmrig
        dest: /opt/zephyr/xmrig
        owner: root
        group: root
        mode: '0744'
    - name: Scp run.sh
      ansible.builtin.copy:
        src: ./scrypts/gary_run.sh
        dest: /opt/zephyr/run.sh
        owner: root
        group: root
        mode: '0744'
    - name: Check xmrig process
      shell: ps aux | grep 'xmrig' | grep -v grep
      register: xmrig_process
      ignore_errors: yes
      tags:
        - always
    - name: Run xmrig
      shell: "( ./run.sh {{ ansible_ssh_host }} > /dev/null 2>&1 &)"
      # shell: "( ./run.sh > /dev/null 2>&1 &)"
      args:
        chdir: /opt/zephyr/
      async: 10 # 最长等待10秒返回
      poll: 0 # 值为0表示无需等待该任务返回
      tags:
        - runminer
      when: xmrig_process.rc != 0
    - name: Stop xmrig
      shell: killall xmrig
      when: xmrig_process.rc == 0
      tags:
        - stopminer

# 准备，然后启动 ansible-playbook -i ./local.hosts.conf local.playbooks.yaml --skip-tags "stopminer"
# 启动 ansible-playbook -i ./local.hosts.conf local.playbooks.yaml --tags "runminer"
# 停止 ansible-playbook -i ./local.hosts.conf local.playbooks.yaml --tags "stopminer"