- name: Start
  hosts: {{ group }}
  gather_facts: yes

  become: true
  roles:
    - zabbix_agent2
  tasks:
    - name: Ping
      ansible.builtin.ping:
    # - name: debug2
    #   shell: pwd
    #   register: result
    # - debug: var=result
    

# - name: Install monitor
#   hosts: {{ group }}
#   gather_facts: yes
#   # vars:
#   #   zabbix_agent_hostname: "{{ ansible_eno2['ipv4']['address'] }}"
#   vars_files:
#     - "vars/zabbix.yaml"
#   become: true
#   tasks:
#     - name: Ping
#       ansible.builtin.ping:
#     - name: debug
#       debug: var=zabbix_agent_hostname
#   roles:
#     - zabbix-agent2
