- name: Uninstall zabbix-agent in Centos7
  yum: 
    name: "zabbix-agent"
    state: "absent"
    autoremove: yes

- name: Install zabbix rpm from a remote repo
  yum:
    # name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-agent2-5.0.9-1.el7.x86_64.rpm
    state: present

- name: Install zabbix_agent2 service
  yum: 
    name: "zabbix-agent2"

- name: Install sysstat tool in Centos7
  yum: 
    name: "sysstat"

- name: Scp items configuration
  template:
    src: ./files/centos7.conf
    dest: /etc/zabbix/zabbix_agent2.d/centos7.conf
    owner: root
    group: root
    mode: '0644'