- name: Install zabbix rpm
  yum:
    name: "https://repo.zabbix.com/zabbix/5.4/rhel/7/x86_64/zabbix-release-5.4-1.el7.noarch.rpm"

- name: Install zabbix_agent2 service
  yum: 
    name: "zabbix-agent2"