- name: Stop zabbix_agent service
  ignore_errors: true
  systemd: 
    name: "zabbix-agent"
    enabled: no
    state: stopped

- name: "Install zabbix-agent2 service in ubuntu16 or ubuntu20"
  include: ./roles/zabbix_agent2/tasks/ubuntu16or20.yaml
  when:
    - ansible_facts['os_family'] == "Debian"
    # - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "20" or ansible_facts['distribution_major_version'] == "16"

- name: "Install zabbix-agent2 service in centos7 or RedHat"
  include: ./roles/zabbix_agent2/tasks/centos7.yaml
  when:
    - ansible_facts['os_family'] == "CentOS" or ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"

- name: Config zabbix_agent2.conf
#   template: src=./files/zabbix_agent2.conf.j2 dest=/etc/zabbix/zabbix_agent2.conf
  template:
    src: ./files/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'

- name: Start zabbix_agent2 service
  systemd: 
    name: "zabbix-agent2"
    enabled: yes
    state: restarted

- name: Checking zabbix-agent2 service status
  shell: ps -ef | grep zabbix_agent2 | grep -v "grep" | awk '{print $2}'
  register: result

- name: showing report
  debug:
    var: result.rc
    
# - name: "Install zabbix-agent2 service successfully"
#   set_fact:
#     install_zabbix_agent2_success: true