- name: Stop zabbix_agent service
  ignore_errors: yes
  systemd: 
    name: "zabbix-agent"
    enabled: no
    state: stopped

- name: "Install zabbix-agent2 service in ubuntu16 or ubuntu20"
  include: ./roles/zabbix_agent2/tasks/ubuntu16or20.yaml
  when:
    - ansible_facts['os_family'] == "Debian"
    # - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "20" or ansible_facts['distribution_major_version'] == "16"

- name: "Install zabbix-agent2 service in centos7"
  include: ./roles/zabbix_agent2/tasks/centos7.yaml
  when:
    - ansible_facts['os_family'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Config zabbix_agent2.conf
#   template: src=./files/zabbix_agent2.conf.j2 dest=/etc/zabbix/zabbix_agent2.conf
  template:
    src: ./files/zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'

- name: Start zabbix_agent2 service
  systemd: 
    name: "zabbix-agent2"
    enabled: yes
    state: restarted

