- name: Install mysql5.7
  yum:
    name: "http://repo.mysql.com/mysql57-community-release-el7-10.noarch.rpm"

- name: Start mysql service
  ansible.builtin.systemd: 
    name: mysqld
    enabled: yes
    state: started
