- name: zephyr_xmrig
  hosts: "{{ hosts }}"
  become: true
  gather_facts: false
  tasks:
    - name: Creates directory
      ansible.builtin.file:
        path: /opt/zephyr
        state: directory
        mode: '0744'
    - name: Scp xmrig
      ansible.builtin.copy:
        src: ./files/local_xmrig # https://github.com/xmrig/xmrig/releases/download/v6.20.0/xmrig-6.20.0-linux-x64.tar.gz
        dest: /opt/zephyr/xmrig
        owner: root
        group: root
        mode: '0744'
    - name: Scp run.sh
      ansible.builtin.copy:
        src: ./files/local_zeph_run.sh
        dest: /opt/zephyr/run.sh
        owner: root
        group: root
        mode: '0744'
    - name: Check xmrig process
      shell: ps aux | grep 'xmrig' | grep -v grep
      register: xmrig_process
      ignore_errors: yes
      tags:
        - always
    - name: Run xmrig
      shell: "( ./run.sh {{ ansible_ssh_host }} > /dev/null 2>&1 &)"
      # shell: "( ./run.sh > /dev/null 2>&1 &)"
      args:
        chdir: /opt/zephyr/
      async: 20 # 设置任务为异步模式，并且定义任务的超时时间。
      poll: 0 # 定义多久检查一次异步任务状态，直到任务完成或超时，默认值为 10 秒。值为0表示无需等待该任务返回。
      tags:
        - startminer
      when: xmrig_process.rc != 0
    - name: Stop xmrig
      shell: killall xmrig
      when: xmrig_process.rc == 0
      tags:
        - stopminer