- name: install zabbix_agent service
  yum:
    name: "https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm"
- name: start zabbix_agent
  systemd: 
    name: "zabbix-agent"
    enabled: yes
    state: started

- name: change zabbix_agentd.conf Hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Hostname=Zabbix server'
    line: "Hostname={{ 等待更新 }}"
  become: yes
    
- name: change zabbix_agentd.conf ServerActive
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'ServerActive=127.0.0.1'
    line: "ServerActive={{ zabbix_server_ip }}"
  become: yes

- name: change zabbix_agentd.conf Server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    state: present
    regexp: 'Server=127.0.0.1'
    line: "Server={{ zabbix_server_ip }}"
  become: yes

- name: restart zabbix_agent
  systemd: 
    name: "zabbix-agent"
    enabled: yes
    state: restarted
