- name: "Initialize Ubuntu20 System"
  include: ./roles/init/tasks/ubuntu20.yaml
  when:
    - ansible_facts['os_family'] == "Debian"
    # - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_major_version'] == "20" or ansible_facts['distribution_major_version'] == "16"

- name: "Initialize Centos7 or RedHat System"
  include: ./roles/init/tasks/centos7.yaml
  when:
    - ansible_facts['os_family'] == "CentOS" or ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
